import os
import yt_dlp
import requests
from pyrogram import Client, filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton, CallbackQuery

# Ayarlar
API_ID = int(os.environ.get("API_ID", "12345"))
API_HASH = os.environ.get("API_HASH", "hash_kodun")
BOT_TOKEN = os.environ.get("BOT_TOKEN", "bot_tokenin")

app = Client("ht_media_bot", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN)

# --- COOKIE YÜKLƏMƏ FUNKSİYASI (Kuki birbaşa daxil edildi) ---
def get_cookies():
    cookie_content = """# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by Cookie-Editor
.youtube.com	TRUE	/	FALSE	1770553992	ST-16vjsij	csn=ZdphBRqo2BR9ChHK&itct=CBIQ-I8FGAEiEwiLgeTH88mSAxUKRfsEHZpGA8oyDGF0b20tYWNjb3VudMoBBHpt9mI%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1787134777	VISITOR_PRIVACY_METADATA	CgJBWhIEGgAgZA%3D%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1770554099	YTSESSION-1nge1wu	ANPz9KimZurdHzcemJx0NHMsM+ezPMo/xrrTjuWNFqbTLXiHyQZprl+JsRqVX+7/I7Qa6kyee8BCudZWruIc5Dzrb6RPw2z1aTw=
#HttpOnly_.youtube.com	TRUE	/	TRUE	1770554092	YTSESSION-rvkia	ANPz9KiHTtVkrrtS6RechnQOJteCVWj2dbXsYyPozvyPtWB6Q0g7dan6FMZj33bVhW/3+aXy4zoNovuHULjD67aqX1dZiJS/KcmvTyckc07xblqpqXIUFFwbS97WcB10tOQSHE5nKcJQdJNMHcyzP1TDlbCFoxkhMwBaByvn3hi67Ago19dkDq0SaspCj5XRexX6zcTmbM3tlSb4uME1zXOFIF8tmAjy/BX5LD9tC18gRNJNfjI5807cw8ta8VMlbd++DBMXvuQ9HuqVoDpyF0fitfCreCq1hBcXOlPu8rZ1dY2tt/4UE58uzskPlgL+nsXjuQGOgnFsExDb+j7MqjYzfBmWPGOHF/SzdCMA7KX9Ff8Ca12C94LKsg==
#HttpOnly_.youtube.com	TRUE	/	TRUE	1833635392	__Secure-3PSID	g.a0006ggty-yJOzYodgLsZFqDLQCXpo7_ZP9TOhnFCzy6z9vC-JvEral8u4H86dzEm7NlixJkDAACgYKARASARMSFQHGX2Miz57Pg670vr1VayLYd61XCRoVAUF8yKopQ0wFDOiQdFv9BNCGM71c0076
.youtube.com	TRUE	/	FALSE	1770553899	ST-v8bavx	csn=TvPkNsJv-xWfayDG&itct=CIgBEIf2BBgAIhMIkr2ym_PJkgMVrJknAh1hIigcWg9GRXdoYXRfdG9fd2F0Y2iaAQUIJBCOHsoBBJ8Pm1Q%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1770565073	GPS	1
.youtube.com	TRUE	/	FALSE	1803118779	SIDCC	AKEyXzVIMj3QjocknAvyDuhiEy4nNNVempJbTMW_dR3msLE9vxVeLoGRUkduHo1mxBR0FOl0
.youtube.com	TRUE	/	FALSE	1770505886	ST-g8223b	csn=FKuFvdMlc6a6-gZW&itct=CFwQ_FoiEwioqcWVwMiSAxWIsCcCHaBgJWoyCmctaGlnaC1yZWNaD0ZFd2hhdF90b193YXRjaJoBBhCOHhieAcoBBJ8Pm1Q%3D
.youtube.com	TRUE	/	FALSE	1770484928	ST-1ewfh0q	csn=3GCtHiYkEV-RgUvH&itct=CFkQrKoBGAAiEwjT6Pmk8seSAxVxaHoFHQTZNAIyCmctaGlnaC1jcHdaCUZFbGlicmFyeZoBBwi4ARDv8AXKAQSfD5tU
#HttpOnly_.youtube.com	TRUE	/	TRUE	1771669191	YSC	QYrJ-S7eT7w
.youtube.com	TRUE	/	FALSE	1833635392	SID	g.a0006ggty-yJOzYodgLsZFqDLQCXpo7_ZP9TOhnFCzy6z9vC-JvEZRUu6tffq0yXTTuM76JzZwACgYKAVASARMSFQHGX2Mi-0ET1y5s507pTVY09olxSBoVAUF8yKrE4ryaxL77J0trFk_z-Y9D0076
.youtube.com	TRUE	/	FALSE	1770485233	ST-s95r78	csn=5LnjntRkTq0GlWve&itct=CIMBEIf2BBgCIhMI1Iqxu_LHkgMVfNHKAB33shhAWg9GRXdoYXRfdG9fd2F0Y2iaAQUIJBCOHsoBBJ8Pm1Q%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1802099389	__Secure-1PSIDTS	sidts-CjUB7I_69FuAyCqhIPnF-S-1UyQFaeEvAvO4hfVKv0LwCVia4pZhWnoC33g390HClJT-IZNjSBAA
.youtube.com	TRUE	/	TRUE	1770554247	CONSISTENCY	AAsGu9nkoArso9RFtPJzUFJDEPAmMlYxZTc1xSIWorEcTUxij8eKi8zBERlmDSYaK3DY4czpsI1oamOrtJF2CuLV2pvIXT-Yd717JllQKuOjPucZHl5dzi5iNaXdOFPJf_VkcTVMPcfwfGD_9A
.youtube.com	TRUE	/	FALSE	1770563272	ST-wv7pqz	csn=UJk-OyD6rWeg2YxE&itct=CAYQ6qgHGAAiEwjclJWSlsqSAxVVZnoFHddrKAfKAQR6bfZi
.youtube.com	TRUE	/	TRUE	1833635392	SAPISID	-jsmqXiqAyqO-uyC/AJaiwKJz8YaPAEGj4
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803118779	__Secure-1PSIDCC	AKEyXzVTSsj2KwlTp8cbsjpOcRyyb3VlcOinj7axjmRHA2r73DUPnGxg7aSaOBnBcIVG0c9T
#HttpOnly_.youtube.com	TRUE	/	TRUE	1833635392	SSID	ATKKKAnfylTNRQ1qg
.youtube.com	TRUE	/	FALSE	1770553902	ST-750j5z	csn=hSTOtNb6WGHmmdRb&itct=CFgQnaQHGAAiEwiGy_-e88mSAxXTDHsEHaF8J25aCUZFbGlicmFyeZoBBwi4ARDv8AXKAQSfD5tU
.youtube.com	TRUE	/	TRUE	1833635392	__Secure-1PAPISID	-jsmqXiqAyqO-uyC/AJaiwKJz8YaPAEGj4
#HttpOnly_.youtube.com	TRUE	/	TRUE	1833635392	__Secure-1PSID	g.a0006ggty-yJOzYodgLsZFqDLQCXpo7_ZP9TOhnFCzy6z9vC-JvEkcaBCMPhPkvCDRVgc0Ej8QACgYKASMSARMSFQHGX2MiXRREislQPPPjDHryKnmYlxoVAUF8yKqjL1c2Az9-9g7ATR9cmEjr0076
.youtube.com	TRUE	/	TRUE	1833635392	__Secure-3PAPISID	-jsmqXiqAyqO-uyC/AJaiwKJz8YaPAEGj4
#HttpOnly_.youtube.com	TRUE	/	TRUE	1803118779	__Secure-3PSIDCC	AKEyXzVBI7OoDxF0d-ORU6Xa75yT-EUV1Vxj422KhBJRAphSOKkV4CcHp1ZNAs-GdchNzLR0Hg
#HttpOnly_.youtube.com	TRUE	/	TRUE	1802099389	__Secure-3PSIDTS	sidts-CjUB7I_69FuAyCqhIPnF-S-1UyQFaeEvAvO4hfVKv0LwCVia4pZhWnoC33g390HClJT-IZNjSBAA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1787134777	__Secure-ROLLOUT_TOKEN	CNGOq9_o7MqtlQEQ2_-20fHHkgMY-pOHkeznkgM%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1787134776	__Secure-YNID	16.YT=aGCwII6ncL1dWNOOUbhysy_NYG2lri-PpYmM7fJW7WcD9pWcTMsXNtmnLz7u5xnXpHlycQCTZbdd5axSOU2QqjmN46cxiMZHjvqFieLZcaLEm-wQC_wZnv1BR8Y1ONu8uHCOSDI9_29m_VTe3eeYFb47FKvk4VuFo6JDYN81J5xsv3yM93_otPWjNHTXEItE4Edkqm_2Ser4vA_BReF4oHfKbEUKYRMNu9SG5spJjE9UTY-efmIFlOMTN7wHvWfLczB5ALMvreBZ9IHWY2zS4zQ0nbKrp7KI6eOT4Uip4Tbncd6tPhwq-lI25gbK4GTfCjFJeqiPgPL-5A5ruhUZzg
.youtube.com	TRUE	/	FALSE	1833635392	APISID	SoZ4K8wvcb9BNzWx/AZTncz4ovXi4SMKI5
#HttpOnly_.youtube.com	TRUE	/	FALSE	1833635392	HSID	AwKGI_ZQnM4lfjbHA
#HttpOnly_.youtube.com	TRUE	/	TRUE	1833635392	LOGIN_INFO	AFmmF2swRAIgBDXL2rBMf1_e5SHLppfpVuHyvrsg27eRNaiZIoUsgeICIEQUjkGsREXzRIikI1tvP_goqPdnEXLZdNXW2HepntGi:QUQ3MjNmeUswSTF0Q0VVTVBRNVJoTU5iVmwwU01UWnlfZXJJZVJuU2NXdlhtRTg4TkkxNzFQRjhXelNQYmlXVkU1MkFkTEhnUU9vTTlsUVZzRHpuUWJFZndOSmt2dGozckFKTFAwSG5mVTFGMXdiRk1tRGNPZjRLekZWa1BxQU9RRlBLYVg0VXFJRHdhbXFmVmxwYlpLcXhZVmdhQUxaYkRB
.youtube.com	TRUE	/	TRUE	1834654777	PREF	tz=Asia.Baku
.youtube.com	TRUE	/	FALSE	1770484929	ST-143rz7l	csn=3GCtHiYkEV-RgUvH&itct=CBsQ08wBGAAiEwjT6Pmk8seSAxVxaHoFHQTZNAIyBmctaGlnaMoBBJ8Pm1Q%3D
.youtube.com	TRUE	/	FALSE	1770505904	ST-143rzh2	csn=ojKeH5JZ4jrjb90E&itct=CBgQ08wBGAEiEwiSsbC2wMiSAxVlQR0JHY26O-AyBmctaGlnaMoBBJ8Pm1Q%3D
.youtube.com	TRUE	/	FALSE	1770554199	ST-174zk57	csn=RwINuLQksYeHHQix&itct=CAUQ5rwGGAUiEwjK7Puq9MmSAxUTgIwIHc_-EB7KAQR6bfZi
.youtube.com	TRUE	/	FALSE	1770484947	ST-17pm9r8	csn=3GNYlxAewFUSBnAv&itct=CBoQp4EJGAAiEwjFr6mi8seSAxXwyw0JHRibPabKAQSfD5tU
.youtube.com	TRUE	/	FALSE	1770554198	ST-1afjx4n	csn=RwINuLQksYeHHQix&itct=CAIQ39wCGAciEwjK7Puq9MmSAxUTgIwIHc_-EB7KAQR6bfZi
.youtube.com	TRUE	/	FALSE	1770485216	ST-1ozzxus	csn=5LnjntRkTq0GlWve&itct=CIcBEIf2BBgBIhMI1Iqxu_LHkgMVfNHKAB33shhAWg9GRXdoYXRfdG9fd2F0Y2iaAQUIJBCOHsoBBJ8Pm1Q%3D
.youtube.com	TRUE	/	FALSE	1770484983	ST-7be7hr	csn=5LnjntRkTq0GlWve&itct=CDkQ_FoiEwjq6Yq98seSAxW3MboAHVHYGuUyCmctaGlnaC1yZWNaD0ZFd2hhdF90b193YXRjaJoBBhCOHhieAcoBBJ8Pm1Q%3D
.youtube.com	TRUE	/	FALSE	1770553566	ST-p1q8bs	csn=XRkSCTgrbPWnqr63&itct=CIkBEIf2BBgAIhMInsKB_vHJkgMVw85JBx2DaBlOWg9GRXdoYXRfdG9fd2F0Y2iaAQUIJBCOHsoBBJ8Pm1Q%3D
#HttpOnly_.youtube.com	TRUE	/	TRUE	1787134777	VISITOR_INFO1_LIVE	JzY2YDPzxj8
#HttpOnly_.youtube.com	TRUE	/	TRUE	1770563512	YTSESSION-jnufdw	ANPz9KgHMmzPDNiGauwa+DjSVWJjjoTw/lRICzBJBXUrrGOHjWSxLaS0ZD48rDYvSyloPiwCSUDvvTPOzEL8PqhdP+OAAc9s7r4="""
    try:
        with open("cookies.txt", "w", encoding="utf-8") as f:
            f.write(cookie_content.strip())
        return "cookies.txt"
    except:
        return None

# --- YÜKLƏMƏ FUNKSİYASI ---
def download_media(url, mode="video"):
    cookie_file = get_cookies() # Kukiləri daxildən yaradır
    ydl_opts = {
        'format': 'best',
        'outtmpl': 'downloads/%(title)s.%(ext)s',
        'quiet': True,
        'no_warnings': True,
        'nocheckcertificate': True,
        'cookiefile': cookie_file,
        'extractor_args': {'youtube': {'player_client': ['android', 'web']}},
        'params': {'allow_unplayable_formats': True},
        'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36',
    }
    
    if mode == "music":
        ydl_opts['postprocessors'] = [{
            'key': 'FFmpegExtractAudio',
            'preferredcodec': 'mp3',
            'preferredquality': '192',
        }]
    
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        info = ydl.extract_info(url, download=True)
        if not info:
            raise Exception("Media tapılmadı.")
        
        filename = ydl.prepare_filename(info)
        
        is_video = True
        if info.get('ext') in ['jpg', 'png', 'webp', 'jpeg'] or info.get('vcodec') == 'none':
            is_video = False

        return filename, info.get('title', 'Media'), is_video

# --- START MESAJI ---
@app.on_message(filters.command("start") & filters.private)
async def start_handler(client, message):
    text = (
        "✨ **HT ULTIMATE DOWNLOADER** ✨\n\n"
        "🚀 Salam! Mən sosial şəbəkələrdən video, musiqi və şəkil yükləmək üçün nəzərdə tutulmuşam.\n\n"
        "📥 **İstifadə:** Sadəcə linki bura göndərin və ya /youtube yazıb axtarış edin."
    )
    buttons = InlineKeyboardMarkup([
        [InlineKeyboardButton("📚 Dəstəklənən Platformalar", callback_data="help_list")],
        [InlineKeyboardButton("📢 Bot Kanalı", url="https://t.me/ht_bots"),
         InlineKeyboardButton("👨‍💻 Sahib", url="https://t.me/kullaniciadidi")]
    ])
    await message.reply_text(text, reply_markup=buttons)

# --- YOUTUBE AXTARIŞ KOMANDASI ---
@app.on_message(filters.command("youtube") & filters.private)
async def youtube_search(client, message):
    query = message.text.split(None, 1)
    if len(query) < 2:
        return await message.reply_text("❌ **Zəhmət olmasa axtarış sözünü yazın!**\nNümunə: `/youtube mahnı adı`")
    
    status = await message.reply("🔍 **YouTube-da axtarılır...**")
    search_query = query[1]
    
    ydl_opts = {'quiet': True, 'no_warnings': True, 'cookiefile': get_cookies()}
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
        try:
            results = ydl.extract_info(f"ytsearch5:{search_query}", download=False)['entries']
            if not results:
                return await status.edit("❌ **Heç bir nəticə tapılmadı!**")
            
            buttons = []
            for video in results:
                title = (video.get('title')[:35] + "..") if len(video.get('title')) > 35 else video.get('title')
                v_url = video.get('webpage_url')
                buttons.append([InlineKeyboardButton(f"🎬 {title}", callback_data=f"yt_choice|{v_url}")])
            
            await status.edit(f"🔎 **'{search_query}' üçün nəticələr:**", reply_markup=InlineKeyboardMarkup(buttons))
        except Exception as e:
            await status.edit(f"❌ **Axtarış xətası:** {str(e)}")

# --- ƏSAS MƏNTİQ ---
@app.on_message(filters.text & filters.private)
async def main_logic(client, message):
    url = message.text
    if url.startswith("/"): return

    if "youtube.com" in url or "youtu.be" in url:
        buttons = InlineKeyboardMarkup([
            [InlineKeyboardButton("🎬 Video", callback_data=f"vid|{url}"),
             InlineKeyboardButton("🎵 Musiqi (MP3)", callback_data=f"mus|{url}")]
        ])
        await message.reply_text("🎞 **YouTube aşkarlandı! Seçim edin:**", reply_markup=buttons)
    
    else:
        status = await message.reply("⚡ **Analiz edilir...** 📥")
        try:
            path, title, is_video = download_media(url, mode="video")
            await status.edit("📤 **Serverə yüklənir... 🚀**")
            
            if is_video:
                await message.reply_video(path, caption=f"✅ **Video:** `{title}`\n🚀 @ht_bots")
            else:
                await message.reply_photo(path, caption=f"✅ **Şəkil:** `{title}`\n🚀 @ht_bots")
            
            await status.delete()
            if os.path.exists(path): os.remove(path)
        except Exception as e:
            await status.edit(f"❌ **Xəta:** {str(e)}")

# --- CALLBACK EMALÇISI ---
@app.on_callback_query()
async def callback_handler(client, callback_query: CallbackQuery):
    data = callback_query.data

    if data.startswith("yt_choice|"):
        url = data.split("|")[1]
        buttons = InlineKeyboardMarkup([
            [InlineKeyboardButton("🎬 Video", callback_data=f"vid|{url}"),
             InlineKeyboardButton("🎵 Musiqi (MP3)", callback_data=f"mus|{url}")]
        ])
        await callback_query.message.edit("⏬ **Formatı seçin:**", reply_markup=buttons)

    elif data == "help_list":
        help_text = (
            "🚀 **Dəstəklənən Platformalar və İmkanlar:**\n\n"
            "📹 **Sosial Media:**\n"
            "• `YouTube` - Video (4K), Shorts, MP3\n"
            "• `TikTok` - Loqosuz videolar\n"
            "• `Instagram` - Reels, Post, Hekayə\n"
            "• `Pinterest` - Video və Yüksək keyfiyyətli Şəkillər\n"
            "• `Facebook` - Bütün kütləvi videolar\n"
            "• `Snapchat` - Spotlight videoları\n\n"
            "🐦 **Xəbər & Forum:**\n"
            "• `Twitter (X)` - Video və GIF\n"
            "• `Reddit` - Səsli videolar\n"
            "• `Threads` - Video yükləmə\n\n"
            "🎵 **Musiqi:**\n"
            "• `SoundCloud`, `Spotify`, `Bandcamp` (MP3 formatda)\n\n"
            "🎬 **Və 1000-dən çox sayt:**\n"
            "• `Vimeo`, `Twitch`, `Dailymotion`, `Steam` ve s."
        )
        await callback_query.message.edit(help_text, reply_markup=InlineKeyboardMarkup([
            [InlineKeyboardButton("⬅️ Geri", callback_data="back_start")]
        ]))

    elif data == "back_start":
        text = (
            "✨ **HT ULTIMATE DOWNLOADER** ✨\n\n"
            "🚀 Salam! Mən sosial şəbəkələrdən video, musiqi və şəkil yükləmək üçün nəzərdə tutulmuşam.\n\n"
            "📥 **İstifadə:** Sadəcə yükləmək istədiyiniz medianın linkini bura göndərin."
        )
        buttons = InlineKeyboardMarkup([
            [InlineKeyboardButton("📚 Dəstəklənən Platformalar", callback_data="help_list")],
            [InlineKeyboardButton("📢 Bot Kanalı", url="https://t.me/ht_bots"),
             InlineKeyboardButton("👨‍💻 Sahib", url="https://t.me/kullaniciadidi")]
        ])
        await callback_query.message.edit(text, reply_markup=buttons)

    elif "|" in data:
        mode_raw, url = data.split("|")
        mode = "video" if mode_raw == "vid" else "music"
        await callback_query.message.edit(f"⏳ **Hazırlanır...** ({mode.upper()})")
        
        try:
            path, title, is_video = download_media(url, mode=mode)
            if mode == "video":
                await callback_query.message.reply_video(path, caption=f"🎬 `{title}`\n🚀 @ht_bots")
            else:
                final_path = path.rsplit('.', 1)[0] + ".mp3"
                if not os.path.exists(final_path): final_path = path
                await callback_query.message.reply_audio(final_path, caption=f"🎵 `{title}`\n🚀 @ht_bots")
                if os.path.exists(final_path) and final_path != path: os.remove(final_path)
            
            await callback_query.message.delete()
            if os.path.exists(path): os.remove(path)
        except Exception as e:
            await callback_query.message.edit(f"❌ **Xəta:** {str(e)}")

app.run()
